/********************************************************
 * Copyright (c) 2004-2022, Brick Technologies Co., Ltd
 * All rights reserved.
 * Home page:http://www.bricktou.com
********************************************************/
/**
 * Language keywords
 */
#pragma once

#define NOTEXISTS   -1

enum node_kind
{
    isunknow = 0,
    isannotation    = 1,
    isnote,
    isnumber,
    isoper,
    isstring,
    islabel,
    
    lankey,
    lanfunc,
    
    temptype,
    
    libmacro,
    libtype,
    libmember,
    libvar,
    libfunc,
    
    libspace,
    libpackage,
    libmodule,
    
    usertable,
    usercolumn,
    userrecord,
    userelement,
    userprocedure,
    
    usermacro,
    usertype,
    usermember,
    uservar,
    userfunc,
    userparam,
    
    userspace,
    userpackage,
    usermodule,
    
    islambda,
};

enum type_kind
{
    unsolved = 0,
    isvoid   = 1,
    isbit,
    isbool,
    isbyte,
    isvarbyte,
    ischar,
    isvarchar,
    iswchar,
    isshort,
    isbyte3,
    isint,
    islong,
    islonglong,
    isfloat,
    isdouble,
    isbigfloat,
    isbigdouble,
    
    isdecimal,
    isbigdecimal,
    
    isdate,
    istime,
    isdatetime,
    istimestamp,
    isyear,
    ismonth,
    isday,
    ishour,
    isminute,
    issecond,
    ismillisecond,
    ismicrosecond,
    
    isenum,
    isstruct,
    isunion,
    isclass,
    isinterface,
    
    isrecord,
    /**
     * text blob clob...
     */
    isobject,
    isauto,
    isanalyst,
};

enum stmt_kind
{
    nokind,
    defmacro,
    defnamespace,
    defpackage,
    defmodule,
    defclass,
    deftype,
    defvariable,
    defprocedure,
    deffunction,
    usingstmt,
    importstmt,
    exportstmt,
    newclass,
    begindecl,
    enddecl,
    sqlstmt,
};
enum key_word
{
    notiskey = 0,
    keyabsolute = 1,
    keyabstract,
    keyadd,
    keyagainst,
    keyaggregate,
    keyalignas,
    keyall,
    keyallocate,
    keyalter,
    keyanalyze,
    keyand,
    keyany,
    keyas,
    keyasc,
    keyasm,
    keyassert,
    keyatomic,
    keyattribute,
    keyauthid,
    keyauto,
    
    keybegin,   // +20
    keybeginwork,
    keybetween,
    keybigint,
    keybinary,
    keyblob,
    keybody,
    keybool,
    keyboolean,
    keybreak,
    keybulk,
    keyby,
    keybyte,
    
    keycall,    // +32
    keycase,
    keycatch,
    keychar,
    keycharacter,
    keycheck,
    keycilk_for,
    keycilk_spawn,
    keycilk_sync,
    keyclass,
    keyclob,
    keyclose,
    keycollate,
    keycollect,
    keycollection,
    keycolumn,
    keycomment,
    keycommit,
    keycommitwork,
    keyconnect,
    keyconst,
    keyconstraint,
    keyconstexpr,
    keycontinue,
    keycreate,
    keycurrent,
    keycursor,
    
    keydatabase,    // +58
    keydate,
    keydatetime,
    keyday,
    keydeallocate,
    keydebug,
    keydeclare,
    keydecltype,
    keydefault,
    keydefine,
    keydelete,
    keydesc,
    keydescribe,
    keydescriptor,
    keydiagnostics,
    keydisconnect,
    keydistinct,
    keydiv,
    keydo,
    keydocument,
    keydouble,
    keydrop,
    keyduplicate,
    
    keyelif,        // +81
    keyelse,
    keyend,
    keyenum,
    keyexcept,
    keyexception,
    keyexec,
    keyexecute,
    keyexists,
    keyexit,
    keyexplicit,
    keyexport,
    keyexports,
    keyextends,
    keyextension,
    keyextern,
    
    keyfalse,   // +98
    keyfetch,
    keyfinal,
    keyfinally,
    keyfirst,
    keyfloat,
    keyfor,
    keyforall,
    keyforeach,
    keyforeign,
    keyfound,
    keyfraction,
    keyfree,
    keyfriend,
    keyfrom,
    keyfull,
    keyfunction,
    
    keyget,     // +115
    keygoto,
    keygrant,
    keygroup,
    
    keyhaving,
    keyhour,
    
    keyidentified,
    keyif,
    keyimmediate,
    keyimplements,
    keyimport,
    keyin,
    keyinclude,
    keyinclude_next,
    keyindex,
    keyinherit,
    keyinline,
    keyinner,
    keyinsert,
    keyinstanceof,
    keyint,
    keyinterface,
    keyintersect,
    keyinterval,
    keyinto,
    keyis,
    keyisnotnull,
    keyisnull,
    keyisolation,
    keyiterate,
    
    keyjoin,
    
    keykey,
    
    keylast,
    keyleave,//mysql leave
    keyleft,
    keylength,
    keylet,
    keylike,
    keylimit,
    keylisting,
    keyload,
    keylock,
    keylong,
    keyloop,
    
    keymap,//Oracle map index
    keymaster,
    keymatch,
    keymatched,
    keymatches,
    keymediumint,
    keymediumtext,
    keymember,
    keymerge,
    keyminute,
    keymodel,
    keymoify,
    keymodule,
    keymoney,
    keymonth,
    keymutable,
    
    keynamespace,
    keynative,
    keynatural,
    keynew,
    keynext,
    keynocase,
    keynoexcept,
    keynolock,
    keynoreturn,
    keynot,
    keynotbetween,
    keynotexists,
    keynotfound,
    keynotin,
    keynotlike,
    keynotmatch,
    keynotmatched,
    keynotmatches,
    keynotregexp,
    keynull,
    keynumber,
    keynumeric,
    
    keyobject,
    keyof,
    keyon,
    keyopen,
    keyoperator,
    keyor,
    keyorder,
    keyout,
    keyouter,
    keyoutput,
    
    keypackage,
    keyparameter,
    keypercent,
    keypipe,
    keypragma,
    keyprepare,
    keyprevious,
    keyprimary,
    keyprior,
    keyprivate,
    keyprocedure,
    keyprotected,
    keypublic,
    keyput,
    
    keyraise,
    keyreal,
    keyrecord,
    keyreference,
    keyregexp,
    keyregister,
    keyrelative,
    keyrename,
    keyrepeat,
    keyreplace,
    keyrestrict,
    keyresume,
    keyreturn,
    keyreturning,
    keyrevoke,
    keyright,
    keyrollback,
    keyrollbackto,
    keyrollbackwork,
    keyrowcount,
    keyrowtype,
    
    keysavepoint,
    keysecond,
    keyselect,
    keysequence,
    keyset,
    keyshort,
    keyskit,
    keysmallint,
    keysql,
    keystart,
    keystatic,
    keystep,
    keystop,
    keystrictfp,
    keystruct,
    keysubtype,
    keysuper,
    keyswitch,
    keysynchronized,
    keysynonym,
    keysystem,
    
    keytable,
    keytemp,
    keytemplate,
    keytext,
    keythen,
    keythis,
    keythrow,
    keythrows,
    keytime,
    keytimestamp,
    keytinyint,
    keytinytext,
    keyto,
    keytop,
    keytrace,
    keytransient,
    keytrigger,
    keytrue,
    keytruncate,
    keytry,
    keytype,
    keytypedef,
    keytypeid,
    keytypename,
    keytypeof,
    
    keyunder,
    keyunion,
    keyunique,
    keyunits,
    keyunload,
    keyuntil,
    keyupdate,
    keyuser,
    keyuses,
    keyusing,
    
    keyvalue,
    keyvalues,
    keyvar,
    keyvarbinary,
    keyvarchar,
    keyvarray,
    keyview,
    keyvirtual,
    keyvoid,
    keyvolatile,
    
    keywhen,
    keywhenever,
    keywhere,
    keywhile,
    keywith,
    keywork,
    
    keyxor,
    
    keyyear,
};
